services:
  pcclim:
    build:
      context: .               
      dockerfile: docker/Dockerfile
    image: pcclim:latest
    container_name: pcclim
    env_file:
      - .env            
    volumes:
      - ./:/app:delegated
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "8000:80"
      - "443:443"              
    restart: unless-stopped
