services:
  pcclim:
    image: pcclim:latest
    container_name: pcclim
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
