 services:
   pcclim:
     image: pcclim:latest
     container_name: pcclim
     env_file:
       - .env
   volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
   ports:
    - "80:80"
    - "443:443"
   restart: unless-stopped
