services:
  pcclim:
    build:
      context: .               
      dockerfile: docker/Dockerfile
    image: pcclim:latest
    container_name: pcclim
    env_file:
      - .env            
    volumes:
      - ./:/app:delegated      
    ports:
      - "8000:80"              
    restart: unless-stopped
