<?php

namespace ContainerON62TKq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoneNumberValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\Constraints\PhoneNumber\PhoneNumberValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\PhoneNumber\PhoneNumberValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/Constraints/PhoneNumber/PhoneNumberValidator.php';

        return $container->privates['App\\Validator\\Constraints\\PhoneNumber\\PhoneNumberValidator'] = new \App\Validator\Constraints\PhoneNumber\PhoneNumberValidator();
    }
}
