<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW2m2Ick\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW2m2Ick/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerW2m2Ick.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerW2m2Ick\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerW2m2Ick\App_KernelProdContainer([
    'container.build_hash' => 'W2m2Ick',
    'container.build_id' => '62baeec0',
    'container.build_time' => 1749888918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW2m2Ick');
