<?php

namespace ContainerW2m2Ick;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoneNumberValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Validator\Constraints\PhoneNumber\PhoneNumberValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\PhoneNumber\PhoneNumberValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\Constraints\\PhoneNumber\\PhoneNumberValidator'] = new \App\Validator\Constraints\PhoneNumber\PhoneNumberValidator();
    }
}
