<?php

namespace ContainerWYCUKic;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Validator\Constraints\Email\EmailValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\Email\EmailValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\Constraints\\Email\\EmailValidator'] = new \App\Validator\Constraints\Email\EmailValidator();
    }
}
