<?php

namespace ContainerSjWr7fw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostalCodeValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\Constraints\PostalCode\PostalCodeValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\PostalCode\PostalCodeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/Constraints/PostalCode/PostalCodeValidator.php';

        return $container->privates['App\\Validator\\Constraints\\PostalCode\\PostalCodeValidator'] = new \App\Validator\Constraints\PostalCode\PostalCodeValidator();
    }
}
