<?php

namespace ContainerSjWr7fw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranslation_Extractor_Visitor_ConstraintService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'translation.extractor.visitor.constraint' shared service.
     *
     * @return \Symfony\Component\Translation\Extractor\Visitor\ConstraintVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/translation/Extractor/Visitor/AbstractVisitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/translation/Extractor/Visitor/ConstraintVisitor.php';

        return $container->privates['translation.extractor.visitor.constraint'] = new \Symfony\Component\Translation\Extractor\Visitor\ConstraintVisitor([0 => 'Email', 1 => 'PhoneNumber', 2 => 'PostalCode', 3 => 'All', 4 => 'AtLeastOneOf', 5 => 'Bic', 6 => 'Blank', 7 => 'Callback', 8 => 'CardScheme', 9 => 'Choice', 10 => 'Cidr', 11 => 'Collection', 12 => 'Compound', 13 => 'Count', 14 => 'Country', 15 => 'CssColor', 16 => 'Currency', 17 => 'DateTime', 18 => 'Date', 19 => 'DivisibleBy', 20 => 'Email', 21 => 'EqualTo', 22 => 'ExpressionSyntax', 23 => 'Expression', 24 => 'File', 25 => 'GreaterThanOrEqual', 26 => 'GreaterThan', 27 => 'Hostname', 28 => 'Iban', 29 => 'IdenticalTo', 30 => 'Image', 31 => 'Ip', 32 => 'IsFalse', 33 => 'IsNull', 34 => 'IsTrue', 35 => 'Isbn', 36 => 'Isin', 37 => 'Issn', 38 => 'Json', 39 => 'Language', 40 => 'Length', 41 => 'LessThanOrEqual', 42 => 'LessThan', 43 => 'Locale', 44 => 'Luhn', 45 => 'NotBlank', 46 => 'NotCompromisedPassword', 47 => 'NotEqualTo', 48 => 'NotIdenticalTo', 49 => 'NotNull', 50 => 'Range', 51 => 'Regex', 52 => 'Sequentially', 53 => 'Time', 54 => 'Timezone', 55 => 'Type', 56 => 'Ulid', 57 => 'Unique', 58 => 'Url', 59 => 'Uuid', 60 => 'Valid', 61 => 'When', 62 => 'Expression', 63 => 'Email', 64 => 'NotCompromisedPassword', 65 => 'When', 66 => 'UniqueEntity', 67 => 'UserPassword']);
    }
}
