<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerON62TKq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerON62TKq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerON62TKq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerON62TKq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerON62TKq\App_KernelDevDebugContainer([
    'container.build_hash' => 'ON62TKq',
    'container.build_id' => 'e8b5a7e2',
    'container.build_time' => 1752489983,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerON62TKq');
