<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMoTWn9A\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMoTWn9A/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMoTWn9A.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMoTWn9A\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMoTWn9A\App_KernelDevDebugContainer([
    'container.build_hash' => 'MoTWn9A',
    'container.build_id' => '5913cdce',
    'container.build_time' => 1753085260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMoTWn9A');
