name: Déploiement sur Lightsail

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Déployer via SSH
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22 # <-- testez en dur d'abord
                  script: |
                      set -e
                      cd ${{ secrets.PROJECT_PATH }}
                      git pull origin main
                      docker compose down
                      docker compose up -d --build
